// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: register.proto

package server

import (
	"context"
	"grpc-common/ucenter/types/register"
	"ucenter/internal/logic"
	"ucenter/internal/svc"
)

type RegisterServiceServer struct {
	svcCtx *svc.ServiceContext
	register.UnimplementedRegisterServiceServer
}

func NewRegisterServiceServer(svcCtx *svc.ServiceContext) *RegisterServiceServer {
	return &RegisterServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *RegisterServiceServer) RegisterByPhone(ctx context.Context, in *register.RegisterRequest) (*register.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.RegisterByPhone(in)
}

func (s *RegisterServiceServer) SendCode(ctx context.Context, in *register.CodeRequest) (*register.NoResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.SendCode(in)
}