// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: register.proto

package ucclient

import (
	"context"
	"grpc-common/ucenter/types/register"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CaptchaRequest   = register.CaptchaRequest
	RegisterRequest  = register.RegisterRequest
	RegisterResponse = register.RegisterResponse
	CodeRequest      = register.CodeRequest
	CodeResponse     = register.NoResponse

	RegisterService interface {
		RegisterByPhone(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
		SendCode(ctx context.Context, in *CodeRequest, opts ...grpc.CallOption) (*CodeResponse, error)
	}

	defaultRegisterService struct {
		cli zrpc.Client
	}
)

func NewRegisterService(cli zrpc.Client) RegisterService {
	return &defaultRegisterService{
		cli: cli,
	}
}

func (m *defaultRegisterService) RegisterByPhone(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	client := register.NewRegisterServiceClient(m.cli.Conn())
	return client.RegisterByPhone(ctx, in, opts...)
}
func (m *defaultRegisterService) SendCode(ctx context.Context, in *CodeRequest, opts ...grpc.CallOption) (*CodeResponse, error){
	client := register.NewRegisterServiceClient(m.cli.Conn())
	return client.SendCode(ctx, in, opts...)
}